In [1]:
import numpy as np

In [3]:
mx_1s = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [6]:
mx_1s=np.ones(5)
print(mx_1s)

[1. 1. 1. 1. 1.]


In [7]:
mx_1s.dtype

dtype('float64')

In [8]:
mx_1s = np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
mx_1s = np.ones((3,4),dtype=int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [11]:
mx_0s = np.zeros((4,5),dtype=int)
print(mx_0s)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [12]:
mx_0s = np.zeros((4,5),dtype=bool)
print(mx_0s)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [13]:
mx_0s = np.zeros((4,5),dtype=str)
print(mx_0s)

[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']]


In [14]:
em_str = ''
print(bool(em_str))

False


In [15]:
em_mx = np.empty((3,3))
print(em_mx)

[[1.83e-322 0.00e+000 0.00e+000]
 [0.00e+000 0.00e+000 4.05e-321]
 [0.00e+000 0.00e+000 0.00e+000]]
