# Numpy Functions

In [2]:
import numpy as np

# arange

In [3]:
#np.arange(start, End, steps)
arr_1d = np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [5]:
odd_arr = np.arange(1,13,2)
print(odd_arr)

[ 1  3  5  7  9 11]


# linespace()

In [9]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

# reshape()

In [12]:
arr_2d = arr_1d.reshape(2,6)
print(arr_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [13]:
arr_2d = arr_1d.reshape(3,4)
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
arr_3d = arr_1d.reshape(2,3,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [20]:
ar=np.arange(1,13).reshape(2,6)
print(ar)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ravel

In [21]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [22]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose()


In [23]:
ar.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])