# Mathemtics operations using Numpy

In [1]:
import numpy as np

In [2]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [4]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [5]:
arr1-arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
np.subtract(arr1,arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [7]:
arr1/arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.divide(arr1/arr2)

ValueError: invalid number of arguments

In [9]:
np.divide(arr1,arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [11]:
arr1@arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [12]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr1.max()

9

In [14]:
arr1.argmax

<function ndarray.argmax>

In [15]:
arr1.argma()

AttributeError: 'numpy.ndarray' object has no attribute 'argma'

In [16]:
arr1.argmax()

8

In [17]:
arr1.max(axis = 0)

array([7, 8, 9])

In [18]:
arr1.min()

1

In [19]:
arr1.argmin()

0

In [20]:
arr1.max(axis=)0

SyntaxError: invalid syntax (<ipython-input-20-30b9b59c5899>, line 1)

In [21]:
arr1.min(axis=0)

array([1, 2, 3])

In [22]:
np.sum(arr1)

45

In [23]:
np.sum(arr1,axis=0)

array([12, 15, 18])

In [24]:
np.sum(arr1,axis=1)

array([ 6, 15, 24])

In [25]:
np.min()

TypeError: _amin_dispatcher() missing 1 required positional argument: 'a'

In [51]:
np.min(arr1)

1

In [26]:
np.mean(arr1)

5.0

In [27]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [28]:
np.std(arr1)

2.581988897471611

In [29]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [30]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [31]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [32]:
arr3=np.arange(1,12).reshape(4,3)

ValueError: cannot reshape array of size 11 into shape (4,3)

In [33]:
arr3=np.arange(1,12).reshape(4,3)
arr4=np.arange(1,12).reshape(4,3)
print(arr3)
print(arr4)

ValueError: cannot reshape array of size 11 into shape (4,3)

In [34]:
arr3=np.arange(1,13).reshape(4,3)
arr4=np.arange(1,13).reshape(4,3)
print(arr3)
print(arr4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [35]:
arr3+arr4

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [36]:
np.add(arr3,arr4)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [37]:
np.subtract(arr3,arr4)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [38]:
np.divide(Arr3,arr4)

NameError: name 'Arr3' is not defined

In [39]:
np.divide(arr3,arr4)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
arr4.argmax()

11

In [41]:
arr4.argmin()

0

In [42]:
arr3.max(axis=0)

array([10, 11, 12])

In [43]:
arr4.min(axis=1)

array([ 1,  4,  7, 10])

In [44]:
np.product(arr1,arr2)

TypeError: only integer scalar arrays can be converted to a scalar index

In [45]:
arr1@arr4

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [46]:
arr3@arr4

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [47]:
arr3*arr3

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]])

In [48]:
arr3@arr4

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [49]:
np.sum(arr3)

78

In [50]:
np.std(arr1)

2.581988897471611

In [52]:
np.exp(arr3)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [53]:
np.sqrt(arr4)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162]])

In [54]:
np.log10(arr4)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251],
       [1.        , 1.04139269, 1.07918125]])