# Random Sampling with numpy

In [1]:
import numpy as np
import random

In [2]:
np.random.random(1)

array([0.4364748])

In [3]:
np.random.random((3,3))

array([[0.06502751, 0.69010027, 0.31617356],
       [0.65909183, 0.58789826, 0.80297174],
       [0.20092654, 0.95582998, 0.39519181]])

In [5]:
np.random.randint(1,4)

3

In [6]:
np.random.randint(1,4,(4,4))

array([[3, 3, 1, 3],
       [2, 2, 3, 2],
       [1, 2, 3, 1],
       [1, 3, 2, 1]])

In [10]:
np.random.randint(1,4,(3,4,4))

array([[[1, 1, 2, 2],
        [3, 1, 1, 3],
        [3, 3, 3, 3],
        [2, 2, 1, 2]],

       [[1, 3, 2, 1],
        [1, 2, 1, 3],
        [1, 3, 1, 1],
        [3, 3, 2, 3]],

       [[2, 1, 2, 3],
        [1, 2, 2, 3],
        [3, 3, 3, 2],
        [1, 2, 3, 3]]])

In [11]:
np.random.seed(10)
np.random.randint(1,4,(3,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]],

       [[2, 2, 2, 3],
        [2, 1, 3, 3],
        [3, 2, 1, 2],
        [2, 1, 3, 2]]])

In [12]:
np.random.seed(10)
np.random.randint(1,4,(3,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]],

       [[2, 2, 2, 3],
        [2, 1, 3, 3],
        [3, 2, 1, 2],
        [2, 1, 3, 2]]])

In [13]:
2**32-1

4294967295

In [14]:
np.random.rand(3)

array([0.60103895, 0.8052232 , 0.52164715])

In [15]:
np.random.rand(3,3)

array([[0.90864888, 0.31923609, 0.09045935],
       [0.30070006, 0.11398436, 0.82868133],
       [0.04689632, 0.62628715, 0.54758616]])

In [16]:
np.random.randn(3,3)

array([[-0.49561818,  0.52563742, -0.38964647],
       [ 0.9372965 , -0.8169742 ,  1.01961544],
       [-0.34143633,  0.7512814 , -0.36225179]])

In [17]:
x=[1,2,3,4]
np.random.choice(x)

3

In [18]:
np.random.choice(x)

2

In [19]:
np.random.choice(x)

3

In [20]:
np.random.choice(x)

3

In [21]:
np.random.choice(x)

4

In [23]:
for i in range(20):
    print(np.random.choice(x))

1
1
1
1
3
3
2
2
4
1
1
3
2
2
4
2
3
2
1
2


In [24]:
x

[1, 2, 3, 4]

In [25]:
np.random.permutation(x)

array([3, 1, 4, 2])

In [26]:
np.random.permutation(x)

array([4, 1, 2, 3])

# Practice

In [27]:
np.random.random(3)

array([0.2350386 , 0.65996495, 0.21495319])

In [28]:
np.random.random((3,3))

array([[0.20304662, 0.38286511, 0.2248728 ],
       [0.1146488 , 0.58301705, 0.23264106],
       [0.55651819, 0.52381088, 0.35095822]])

In [29]:
np.random.random((2,3,4))

array([[[7.05331613e-01, 8.20703741e-01, 1.34563003e-01, 6.04726160e-01],
        [2.83148276e-01, 5.06407820e-01, 3.84604283e-02, 3.32444096e-01],
        [2.72531491e-04, 6.64655466e-01, 3.77440665e-01, 7.47581968e-01]],

       [[1.40575782e-01, 3.88049453e-01, 8.66491641e-01, 9.56853326e-01],
        [4.86553669e-01, 1.05933059e-01, 3.40037289e-01, 8.35570794e-01],
        [4.65441626e-01, 9.28561081e-02, 8.54694143e-01, 3.37258186e-01]]])

In [30]:
np.random.randint(2)

1

In [31]:
np.random.randint(1,10,(3,4))

array([[8, 9, 6, 9],
       [2, 6, 2, 5],
       [8, 8, 8, 8]])

In [32]:
np.random.seed(10)
np.random.randint(1,10,(3,4))

array([[5, 1, 2, 1],
       [2, 9, 1, 9],
       [7, 5, 4, 1]])

In [33]:
np.random.seed(10)
np.random.randint(1,10,(3,4))

array([[5, 1, 2, 1],
       [2, 9, 1, 9],
       [7, 5, 4, 1]])

In [34]:
x=[2,4,8,94,3,5,34,53,67,23]
np.random.choice(x)

3

In [35]:
np.random.choice(x)

34